"""initial schema

Revision ID: ad0ca95d96dc
Revises: 
Create Date: 2026-08-12 10:06:41.013472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0ca95d96dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_log_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.Enum('resident', 'admin', 'system', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('audit_log_id', name=op.f('pk_audit_logs'))
    )
    op.create_table('communities',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('community_id', name=op.f('pk_communities'))
    )
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('resident', 'admin', name='tokensubjecttype'), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.refresh_token_id'], name=op.f('fk_refresh_tokens_replaced_by_token_id_refresh_tokens')),
    sa.PrimaryKeyConstraint('refresh_token_id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('admin_users',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'super_admin', name='adminrole'), server_default='admin', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.community_id'], name=op.f('fk_admin_users_community_id_communities')),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('pk_admin_users'))
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('billing_periods',
    sa.Column('billing_period_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('reading_window_start', sa.Date(), nullable=False),
    sa.Column('reading_window_end', sa.Date(), nullable=False),
    sa.Column('payment_due_date', sa.Date(), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fine_per_day_overdue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open_for_readings', 'readings_closed', 'billed', 'closed', name='billingperiodstatus'), server_default='draft', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.community_id'], name=op.f('fk_billing_periods_community_id_communities')),
    sa.PrimaryKeyConstraint('billing_period_id', name=op.f('pk_billing_periods')),
    sa.UniqueConstraint('community_id', 'period_label', name=op.f('uq_billing_periods_community_id'))
    )
    op.create_table('residents',
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.community_id'], name=op.f('fk_residents_community_id_communities')),
    sa.PrimaryKeyConstraint('resident_id', name=op.f('pk_residents')),
    sa.UniqueConstraint('email', name=op.f('uq_residents_email'))
    )
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_residents_house_number'), ['house_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_residents_mobile_number'), ['mobile_number'], unique=True)

    op.create_table('import_jobs',
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('excel', 'csv', 'google_sheets', name='importsourcetype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'mapped', 'validated', 'confirmed', 'failed', 'cancelled', name='importjobstatus'), server_default='uploaded', nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], name=op.f('fk_import_jobs_admin_id_admin_users')),
    sa.ForeignKeyConstraint(['community_id'], ['communities.community_id'], name=op.f('fk_import_jobs_community_id_communities')),
    sa.PrimaryKeyConstraint('import_job_id', name=op.f('pk_import_jobs'))
    )
    op.create_table('meters',
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('meter_serial_number', sa.String(length=40), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], name=op.f('fk_meters_resident_id_residents')),
    sa.PrimaryKeyConstraint('meter_id', name=op.f('pk_meters'))
    )
    with op.batch_alter_table('meters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meters_meter_serial_number'), ['meter_serial_number'], unique=True)

    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.Enum('resident', 'admin', name='recipienttype'), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('reading_reminder', 'reading_needs_review', 'reading_missing', 'bill_generated', 'bill_overdue', 'payment_reminder', 'payment_received', 'payment_failed', 'fine_applied', 'import_completed', 'billing_cycle_opened', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'sms_mock', 'email_mock', name='notificationchannel'), server_default='in_app', nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=30), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], name=op.f('fk_notifications_admin_id_admin_users')),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], name=op.f('fk_notifications_resident_id_residents')),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_table('otp_requests',
    sa.Column('otp_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('signup', 'login', 'password_reset', name='otppurpose'), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], name=op.f('fk_otp_requests_resident_id_residents')),
    sa.PrimaryKeyConstraint('otp_id', name=op.f('pk_otp_requests'))
    )
    op.create_table('system_configuration',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'int', 'float', 'bool', 'json', name='configvaluetype'), server_default='string', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.admin_id'], name=op.f('fk_system_configuration_updated_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_configuration'))
    )
    op.create_table('import_rows',
    sa.Column('import_row_id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('mapped_data', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.Enum('valid', 'warning', 'error', name='importrowvalidationstatus'), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'skip', name='importrowaction'), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.import_job_id'], name=op.f('fk_import_rows_import_job_id_import_jobs')),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], name=op.f('fk_import_rows_resident_id_residents')),
    sa.PrimaryKeyConstraint('import_row_id', name=op.f('pk_import_rows'))
    )
    op.create_table('meter_readings',
    sa.Column('meter_reading_id', sa.Integer(), nullable=False),
    sa.Column('billing_period_id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('previous_reading_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('submitted_reading_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('raw_digits', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ai_status', sa.Enum('accepted', 'needs_review', 'rejected', name='reviewstatus'), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('ai_validation_notes', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'ai_accepted', 'needs_review', 'rejected', 'resident_confirmed', 'admin_overridden', name='meterreadingstatus'), server_default='submitted', nullable=False),
    sa.Column('submitted_by', sa.Enum('resident', 'admin', name='submittedby'), server_default='resident', nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('final_reading_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('resident_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['billing_period_id'], ['billing_periods.billing_period_id'], name=op.f('fk_meter_readings_billing_period_id_billing_periods')),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.meter_id'], name=op.f('fk_meter_readings_meter_id_meters')),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], name=op.f('fk_meter_readings_resident_id_residents')),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.admin_id'], name=op.f('fk_meter_readings_reviewed_by_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('meter_reading_id', name=op.f('pk_meter_readings')),
    sa.UniqueConstraint('billing_period_id', 'resident_id', name=op.f('uq_meter_readings_billing_period_id'))
    )
    op.create_table('bills',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('billing_period_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('meter_reading_id', sa.Integer(), nullable=True),
    sa.Column('previous_reading_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('current_reading_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('consumption_units', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('issued', 'paid', 'overdue', 'waived', 'cancelled', name='billstatus'), server_default='issued', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['billing_period_id'], ['billing_periods.billing_period_id'], name=op.f('fk_bills_billing_period_id_billing_periods')),
    sa.ForeignKeyConstraint(['meter_reading_id'], ['meter_readings.meter_reading_id'], name=op.f('fk_bills_meter_reading_id_meter_readings')),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], name=op.f('fk_bills_resident_id_residents')),
    sa.PrimaryKeyConstraint('bill_id', name=op.f('pk_bills')),
    sa.UniqueConstraint('billing_period_id', 'resident_id', name=op.f('uq_bills_billing_period_id'))
    )
    op.create_table('fines',
    sa.Column('fine_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('accrual_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], name=op.f('fk_fines_bill_id_bills')),
    sa.PrimaryKeyConstraint('fine_id', name=op.f('pk_fines')),
    sa.UniqueConstraint('bill_id', 'accrual_date', name=op.f('uq_fines_bill_id'))
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('provider_name', sa.String(length=30), nullable=False),
    sa.Column('provider_reference_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('initiated', 'success', 'failed', 'cancelled', name='paymentstatus'), server_default='initiated', nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], name=op.f('fk_payments_bill_id_bills')),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.resident_id'], name=op.f('fk_payments_resident_id_residents')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('fines')
    op.drop_table('bills')
    op.drop_table('meter_readings')
    op.drop_table('import_rows')
    op.drop_table('system_configuration')
    op.drop_table('otp_requests')
    op.drop_table('notifications')
    with op.batch_alter_table('meters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meters_meter_serial_number'))

    op.drop_table('meters')
    op.drop_table('import_jobs')
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_residents_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_residents_house_number'))

    op.drop_table('residents')
    op.drop_table('billing_periods')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    op.drop_table('communities')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
